### ISSUE TITLE
Small new feature request (status bar)

### ISSUE THREAD

**Issue by OrWest** [TimOliver/TOCropViewController#104]
Hello. I'm enjoying use your library in my app. I think that hidden status bar feature will be awesome because in some situation status bar distorts image. Bool property will be great.

![photo](https://cloud.githubusercontent.com/assets/12881398/16221427/55a61426-379b-11e6-9a30-4096862eea9a.jpg)

Thank you.

**Comment by TimOliver** [comment]
Hi @OrWest! Thanks a lot! I'm glad you're enjoying the library!

Oh dear! Hmm okay then. Are you presenting the view controller from a `UINavigationController`? The status bar automatically hides itself if the view controller is presented modally, but for the time being, I made it visible when pushed from a `UINavigationController` since hiding it forces the navigation controller to do a -20 point slide animation upwards which breaks the controller.

It's possible to fix this, but it will be a matter of carefully timing the presentation transition so the status bar is visible until the animation has completed, and then hidden while the offset the navigation controller introduces is compensated.

Sadly, it's not as easy as you might imagine, but if anyone wants to give it a shot, I'd gladly accept a PR for it. :)

**Comment by TimOliver** [comment]
Failing that, I could also just make it so the crop box edges are slightly lower when it detects there is a `UINavigationController` parent. That would be much easier, and would fix this issue too. :)

**Comment by OrWest** [comment]
Earlier I show Cropper via Push in `UINavigationController`, but this method has a lot bugs) So, I show Crop via presenting modally. But status bar hasn't hide if I set `View controller-based status bar appearance` to `NO` in info.plist. I think this key decline calling of `- (BOOL)prefersStatusBarHidden` which tell to hidden status bar)
Now, I inherited of `TOCropViewController` and overrode two methods:

`- (void)viewWillAppear:(BOOL)animated {`
`  [[UIApplication sharedApplication] setStatusBarHidden:YES withAnimation:UIStatusBarAnimationSlide];`
`  [super viewWillAppear:animated];`
`}`

`- (void)viewWillDisappear:(BOOL)animated {`
`  [[UIApplication sharedApplication] setStatusBarHidden:NO withAnimation:UIStatusBarAnimationSlide];`
`  [super viewWillDisappear:animated];`
`} `

**Comment by OrWest** [comment]
#106

**Comment by TimOliver** [comment]
I ended up adding this in the code I needed to add for iPhone X support. It actually turned out to be a lot more complex than I realised since it also implicitly meant the rotating origin of the crop view canvas also needs to be shifted down.

It should all be good now. :D

**Comment by GUDIPATIASHOKREDDY** [comment]
Hi TimOliver. I'm enjoying use your library in my app.how to add navigation bar in cropping view like view controller navigation bar

**Comment by TimOliver** [comment]
Hi @GUDIPATIASHOKREDDY! It's usually better if you open a new issue when asking new questions. :)

The answer is you can't. If you push it to a navigation controller, it hides the navigation bar, but the 'Done' button will integrate with the navigation controller. This view controller was designed to use as much screen space as possible.

There's an option to move the tool bar to the top of the screen, if that helps.

**Comment by GUDIPATIASHOKREDDY** [comment]
Thanks TimOliver.it it possible change status bar color?
