### ISSUE TITLE
to change only image of ToCropView

### ISSUE THREAD

**Issue by NiteshKhandal** [TimOliver/TOCropViewController#115]
**i create ToCropView like:**

        self.cropView = TOCropView()
        self.cropView = TOCropView(image: Image)
        self.cropView.frame = CGRectMake(35, cropView_Y, cropView_Width, cropView_Height)
        self.cropView.backgroundColor = UIColor.clearColor()
        self.view.addSubview(self.cropView)

but i want to change the image of cropView on the tap CollectionView Cell then how do i change image of ToCropView and also i tap again and again.

**my screen look like as below link:**

![simulator screen shot 30-jun-2016 3 46 29 pm](https://cloud.githubusercontent.com/assets/13778681/16616013/0b6bb920-4398-11e6-8dc7-0af0cf61cd3b.png)

**here i have to change image of my cropView when user tap on image shown below in the screen.**

**Comment by TimOliver** [comment]
Oh dear! Okay, I see what you're trying to do now.

I never designed `TOCropView` to allow its image to be switched (I didn't really even intend for it to be used outside of the `TOCropViewController` class!) so as far as I know, it can't handle that.

Probably the quickest and easiest thing to do is to create a new `TOCropView` from scratch whenever the user taps a new image in the collection view. Since this is a user initiated action, this isn't a bad compromise and there shouldn't be any visible performance hits.

Beyond that, it would be necessary to add the image-swapping functionality to `TOCropView` itself.

**Comment by TimOliver** [comment]
I'm going to close this issue now. Feel free to re-open it if you need additional help. :)

**Comment by NiteshKhandal** [comment]
ok , no problem i have solved my issue... :)

**Comment by techoutliers** [comment]
@NiteshKhandal Is it possible to share how you solved your problem?
