### ISSUE TITLE
when I use cropRegionInsets, the aspect ratio can not be set correctly.

### ISSUE THREAD

**Issue by TonnyTao** [TimOliver/TOCropViewController#12]
when I set cropRegionInsets = = UIEdgeInsetsMake(0, 0, 150, 0);
or change the cropView.frame = CGRectMake(0, 0, self.view.bounds.size.width, self.view.bounds.size.height-150);

and adjust aspect ratio to 1:1

the croprect is not a square.

**Comment by TimOliver** [comment]
Can you please paste the code you wrote to present the view controller here?

I originally added `cropRegionInsets` since I was considering adding a navigation bar at the top and this was to define the maximum bounds of the cropping view. That being said, no matter what the region insets are, it shouldn't mess with the aspect ratio.

**Comment by TimOliver** [comment]
Closing this off as it was never followed up.
