### ISSUE TITLE
Feature request: Double tap to zoom would be nice in the cropper

### ISSUE THREAD

**Issue by Pe-te** [TimOliver/TOCropViewController#120]
Just like in the photos app, the point you double tap gets zoomed into.

**Comment by TimOliver** [comment]
Thanks for the feature request!

I just tested it to be sure. The Photos app doesn't do double-tap zooming after you've tapped the 'Edit' button. It only allows that when you're viewing photos normally and not when editing photos (which is what this library is modelled off).

I'd rather not diverge from the expected system functionality where possible since that will reduce how intuitive the library is to users. Additionally, zooming to a `CGPoint` (as opposed to a `CGRect`) is actually a relatively tricky operation, so it would require a fair bit of work and testing to properly integrate into this library.

If you want, feel free to implement it yourself as an optional property, and file a PR! :)

**Comment by Pe-te** [comment]
Ah okay, didn't see the editing mode because we're using the circular cropping style. There it's more like a viewer, so would make sense in my opinion .. at least I tried a double tap when I wanted to zoom into the image.

In another project we let the scroll view handle everything, but not sure my objective c voodoo is strong enough, so I'll leave the swift code here hoping it helps the person who tries to implement it:

`
class ImageZoomViewer : UIScrollViewDelegate {
    override func viewDidLoad() {
        super.viewDidLoad()
        self.scrollView.minimumZoomScale = 1.0
        self.scrollView.maximumZoomScale = 2.0
    }

    override func viewWillLayoutSubviews() {
        super.viewWillLayoutSubviews()
        self.scrollView.zoomScale = self.scrollView.minimumZoomScale
    }
    
    @IBAction func tapOnImageDetected(recognizer: UITapGestureRecognizer) {
        if self.scrollView.zoomScale == self.scrollView.maximumZoomScale {
            self.scrollView.zoomScale = self.scrollView.minimumZoomScale
        } else {
            self.scrollView.zoomScale = self.scrollView.maximumZoomScale
        }
    }
    
    func viewForZoomingInScrollView(scrollView: UIScrollView) -> UIView? {
        return scrollContainer
    }
`
