### ISSUE TITLE
Weird header bar appears at the top, causing misalign between image and crop border

### ISSUE THREAD

**Issue by iori57** [TimOliver/TOCropViewController#15]
I'm getting a weird header bar that appears at the top of the view controller when using this library. It appears both in simulator (iphone 4,5,6 regardless) as well as real device (tested on iPhone 6 plus).

Here's the screenshot of portrait view that causes image and crop border to be not aligned:
![ios simulator screen shot 12 sep 2015 13 56 51](https://cloud.githubusercontent.com/assets/5056279/9830166/9d2d379e-5956-11e5-891c-5c7c4b6d3ea6.png)

And here's a screenshot of landscape view that causes the 'Done' button to be blocked:
![ios simulator screen shot 12 sep 2015 13 57 37](https://cloud.githubusercontent.com/assets/5056279/9830172/b4fe7dce-5956-11e5-918d-6588e4d01909.png)

Anyone facing the same issue?

Meanwhile I will try to debug this on my side as well.

**Comment by TimOliver** [comment]
What the heck? I've never seen that before. :S

What version of iOS is that? And how are you presenting the view controller onscreen (ie navigation controller)?

**Comment by iori57** [comment]
I figured the cause of the problem, the problem was because I thought that the way to use this library is the same as your colleague Kishikawa-san's PEPhotoCropEditor :)

His code example suggested us to present the view controller as such:
UINavigationController *navigationController = [[UINavigationController alloc] initWithRootViewController:controller];
 [self presentViewController:navigationController animated:YES completion:NULL];

However, doing the same while using your library will cause the issue above. I figured that the navigationController was causing the problem so actually we don't need that. This is sufficient:
 [self presentViewController:controller animated:YES completion:NULL];

Tested and works wonderfully. You have trully written the best image crop library for iOS that I have came across. Brilliant work!

Just a suggestion: Would be of great help to others to put a code example on how to initialize and use the library on the first page, like how Kishikawa-san did it :)

Million thanks!

**Comment by TimOliver** [comment]
Ahhhh, yep! That would certainly do it. XD

I never intended the view controller to be pushed to a `UINavigationController`, so I never tried that out. 
Ahaha, yeah, my colleague Katsumi's `PEPhotoCropEditor` is designed to work with a navigation bar running along the top, just like the older system cropper did in iOS 6. But since this one keeps all of its logic in a toolbar along the bottom, it made sense to keep this one exclusively modal (As any navigation bars would be empty).

That's a good idea! I'll definitely have to add some instructions to the README. I might also see if it's worth adding some additional logic to disallow the view controller from being pushed onto a navigation controller.

Thanks a lot for that! I'm glad you're finding this library useful! :)
