### ISSUE TITLE
No longer compiles because of undefined symbols on iOS 10

### ISSUE THREAD

**Issue by MiMo42** [TimOliver/TOCropViewController#188]
SImply no longer compiles on XCode 8.3.3 for <= iOS 10 as symbol UIScrollViewContentInsetAdjustmentNever is iOS 11 only.

And: you cannot successfully compile
self.scrollView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever
for iOS 10 as you cannot access a property that does not exist.
Asking for a SEL to exist does not help us here.
Selectors and properties are not the same.

**Comment by TimOliver** [comment]
Hi @MiMo42!

Oops! Thanks for reporting that to me. I saw the build failed just before bed but I hadn't gotten to checking it yet.

That code works fine in Xcode 9. Properties are just a very specific kind of synthesized method, so it's fine to check for them, but since the API doesn't exist at all in iOS 10's SDK, we needed more.

I've updated it with Apple's preferred availability API and wrapped it in a macro that will ensure it's being built in Xcode 9. Once Xcode 9 goes GM, it'll probably safe to remove the macro check.

Thanks for reporting it to me!
