### ISSUE TITLE
'@param' command used in a comment that is not attached to a function declaration warning

### ISSUE THREAD

**Issue by zarzonis** [TimOliver/TOCropViewController#191]
Hi, I'm using cocoapods and the version 2.1.0 of your library. Also I'm using the latest version Xcode( 8.3.3). 

After upgrading to the latest version of your library I get 9 compile time warnings. This didn't happen with version 2.0.12. The warnings has to do with the documentation of your code.

The warning is the following: '@param' command used in a comment that is not attached to a function declaration warning.

**Comment by TimOliver** [comment]
Hi @zarzonis!

Ah I see why that's happening. The `@param` lines are there to explain each parameter in the block, but since the block itself is a property and not a method, it's confusing the parser.

This issue seems to only be present in Xcode 8. They don't appear in the latest Xcode 9 beta.

Since we're literally days away from the launch of iOS 11 and Xcode 9 now, there's probably no reason trying to come up with a way to fix it when it'll fix itself soon anyway.

I'll leave the issue open in case something happens between now and the Xcode 9 GM

**Comment by zarzonis** [comment]
Hi @TimOliver,

This makes sense. There is no need to fix it then. I'll upgrade my project in the next few days using the Xcode GM.

Best regards,
Spyros

**Comment by TimOliver** [comment]
The Xcode 9 GM is out, and this issue hasn't regressed. I'd say it's safe to close this now. :D

Thanks again for the issue!
