### ISSUE TITLE
Cocoapods v2.1.0: the missing semicolon issue

### ISSUE THREAD

**Issue by andy61i** [TimOliver/TOCropViewController#200]
The current Cocoapods version (2.1.0) still has the missing semicolon issue that is already fixed on Github.

/Users/.../Pods/TOCropViewController/TOCropViewController/TOCropViewController.m:833:50: error: expected ';' at end of declaration
            bool isCallbackOrDelegateHandled = NO
                                                 ^
                                                 ;
1 error generated.

**Comment by semenag01** [comment]
I have same trouble.

**Comment by m4f1h4rd** [comment]
+1

**Comment by TimOliver** [comment]
I'm not set up to be able to work on this project at the moment, sorry folks!

A PR would GREATLY be appreciated. :D

**Comment by michalcichon** [comment]
I created a pull request to fix this issue.

**Comment by camoufleur** [comment]
so, how can fix it?

**Comment by michalcichon** [comment]
@camoufleur Failed code base evolved since 2.1.0 so fixing it should be done by preparing new version from the stabile branch (master) - this is my pull request about (increasing verion number in the cocoapods configuration). After pushing it to the master branch, the library owner - @TimOliver should release it (`pod trunk push`).

**Comment by michalcichon** [comment]
@camoufleur If you're using this library in your application, then you can use a `:git` parameter to download the latest version from GitHub instead of the version registered in Cocoapods.

`pod 'TOCropViewController', :git => 'https://github.com/TimOliver/TOCropViewController.git', :branch => 'master'`

**Comment by TimOliver** [comment]
Okay. I think this is finally resolved. Thanks for all of the input everyone! :)
