### ISSUE TITLE
Swift 4 compatibility?

### ISSUE THREAD

**Issue by ethanwa** [TimOliver/TOCropViewController#204]
Is this library fully Swift 4 compatible? If not, is it on the roadmap? Thanks!

**Comment by TimOliver** [comment]
Hi @ethanwa! What does a library need in order to be Swift 4 compatible exactly?

As an Objective-C library, it can be bridged to any version of Swift, and it was annotated with Swift 3 method names. It SHOULD just work with Swift 4, but I might be missing something.

Let me know! :)

**Comment by ethanwa** [comment]
I’m not sure if there are some syntax changes in the code that need to be made or not. My Swift 4 project with this Pod in it is giving me a warning that is needs to be “converted” to Swift 4.

**Comment by zarzonis** [comment]
@ethanwa The library works fine for me with Swift 4 without doing anything special. I just use the latest version of the library. I recently converted a project I'm working on from Swift 3 to Swift 4 without any problem.

**Comment by vishalvshekkar** [comment]
@zarzonis have you used TOCropViewController through pods or manually in your project?

**Comment by zarzonis** [comment]
@vishalvshekkar I use the latest version using Cocoapods.

**Comment by TimOliver** [comment]
Okay, yeah I'm seeing it too now. I think this is a CocoaPods issue. CocoaPods seems to still be generating its Pods project in Swift 3.2. That's probably on purpose since it's source compatible with Swift 4 so it allows the greatest amount of compatibility, but it's still causing Xcode to complain.

Anyway. I don't think there's anything we can do from this end to improve our compatibility, so I'm going to close this issue.
