### ISSUE TITLE
I find a problem

### ISSUE THREAD

**Issue by Rochester-Ting** [TimOliver/TOCropViewController#216]
![image](https://user-images.githubusercontent.com/16523293/33193423-69870088-d103-11e7-9bc7-774af52cb1c6.png)

![image](https://user-images.githubusercontent.com/16523293/33193438-885ff7da-d103-11e7-8a43-f4443c82b71d.png)

what's wrong

**Comment by TimOliver** [comment]
Hi @Rochester-Ting!

Hmm, that usually happens if the controller was initialized with the `UIImage` being `nil`. It tries to call `image.size`, but because it's `nil`, it causes layout errors in Core Animation.

I thought that the controller had better provisions for checking if `image == nil`, but in any case, the best way to avoid this is to make sure your code only provides valid `UIImage` instances to this library. :)

Hope that helped!
