### ISSUE TITLE
Please fix bug ios 9 uiactionsheet. Thankyou.

### ISSUE THREAD

**Issue by rockkow** [TimOliver/TOCropViewController#23]
Please fix bug ios 9 uiactionsheet warning . Thankyou.

**Comment by TimOliver** [comment]
Thanks a lot for the messages Ro, but in future, please do not spam all of my accounts with the same message. Especially for something that is not even a bug. ;)

Sorry, but I don't have time to update the `UIActionSheet` right now. I had a quick look, but given how greatly the API logic with `UIActionSheet`'s successor, `UIActionController` differs (blocks and delegates), in order to add that, as well as maintain support for `UIActionSheet` (As I'm still using this library for an iOS 7 app), I'll need to significantly refactor that area.

I added pragma mark statements to suppress the warnings for now. It's not elegant, but `UIActionSheet` won't be going anywhere for a while still. I'll be needing to do a pass on this controller to enable split screen support at some point, so I'll do it at the same time. 

In any case, if there's anything else you want to contribute, feel free to add it yourself and file a pull request.
