### ISSUE TITLE
Make background white

### ISSUE THREAD

**Issue by Briahas** [TimOliver/TOCropViewController#245]
- [*] I have read this issue template and provided all possible information. 
- [*] I'm using CocoaPods and have run `pod update` before filing this issue.

## Hardware / Software

**TOCropViewController (2.1.0)**
iOS 10.3.1 (any)
iPhone 7 (any)
CocoaPods 1.3.1

## Goals
I want make background white

## Expected Results
background is white

## Actual Results
Didnt find the way to do this without changing initial framework code.
Commented these lines in `TOCropView.m`:
```
    [self addSubview:self.overlayView];
    .....
    [self addSubview:self.translucencyView];

```
## Steps to Reproduce
In test project try to make background white

**Comment by TimOliver** [comment]
Thanks for filling out all of the information in your issue @Briahas!

There's no official API for changing the background color to white. This view controller is only designed for dark mode.

There are so many translucent and dimming views that simply changing the background to white wouldn't be enough. Additionally, the foreground grid would need to be changed to another color otherwise it wouldn't be visible.

To do this properly, it would probably be necessary to set up a whole light theme / dark theme mechanism. But I sadly don't have the time at the moment.

If you're feeling up to the challenge of adding a light theme to the view controller, here's how I've done it in other libraries: https://github.com/TimOliver/TOScrollBar/blob/master/TOScrollBar/TOScrollBar.m#L154

Good luck!
