### ISSUE TITLE
Nothing happens when I click "done"

### ISSUE THREAD

**Issue by y-spreen** [TimOliver/TOCropViewController#325]
- [x] I have read this issue template and provided all possible information. 
- [x] I'm using CocoaPods and have run `pod update` before filing this issue.

---

## Hardware / Software

- Which version of the library were you using?  

latest

- Which version of iOS are you running?  

latest

- What model of iOS device were you testing on?  

XR emulator

- If using CocoaPods, which version of CocoaPods are you on?  

latest

## Goals

- What is the outcome result you want to achieve with this library? 

.. crop an image?

## Expected Results

 - What did you expect to happen?

picker closes, delegate is called.

## Actual Results

- What happened instead?  (Please attach a screenshot/screen recording if possible)

nothing happens

## Steps to Reproduce

- What are the steps needed to reproduce this issue?
If this bug was caused by a specific image, please post it here.

I used the minimum example from Readme.md

**Comment by y-spreen** [comment]
Okay, so the delegate _is_ called, but the view never closes? How do I close it?

**Comment by y-spreen** [comment]
Okay, you have to call dismiss manually. This **should be added** to the README. The existing readme is not a minimum working example, and this took a while to figure out..

I tried calling `close`, didn't think about `dismiss`.

**Comment by TimOliver** [comment]
Thanks for the issue @y-spreen! Sorry for the delay.

I'll think about it, but I'm not exactly impressed by your tone there. Instead of trying to blackmail me into doing work for you by refusing to close your own issue, did you consider just filing a pull request with your suggestion?

But on that note, I would expect users of this library to have at least a rudimentary knowledge of UIKit to the point where it shouldn't be necessary for me to point literally everything out. It's extremely common practice in Apple's own `UIViewController` subclasses that if you are responsible for presenting the controller, you are also responsible for dismissing the controller from the delegate.

Let me hear your thoughts on this before **I** close this issue. :)

**Comment by y-spreen** [comment]
Thank you for the response. In my personal experience, this library was the first time I encountered the "close it yourself" mentality. And since then, I only came across similar behavior when dealing with the e-mail compose dialog.

What could be possible other use cases that require the same handling? It appears to me, that this library may be the first time a developer ever comes across this practice. Cropping images is a pretty common task.

So I think there is a big potential time safe for new developers if the hint is added. If you can point to official apple documentation regarding the practice, that would be even better. Then the user in common can also learn some good useful habits.

I could have created the pr directly, but I did not feel like I was the right person to write the explanation for it. As you've pointed out, I did not even know that this is common, so it's probably better if I don't put any wrong information in the documentation.
