### ISSUE TITLE
Swift 5 support?

### ISSUE THREAD

**Issue by yarodevuci** [TimOliver/TOCropViewController#342]

**Comment by TimOliver** [comment]
Please do not submit an empty issue.

If you're asking about support for a new Swift version, please write here what actually needs changing.

**Comment by yarodevuci** [comment]
I get a pod conversion to swift 5 needed warning

**Comment by OkiRules** [comment]
He means that he would like TOCropViewController to support the latest Swift 5 and Xcode 10.2

**Comment by alexeybolv** [comment]
Any info about release of the new version with swift 5?

**Comment by yarodevuci** [comment]
@TimOliver

**Comment by TimOliver** [comment]
Don't do that.

**Comment by yarodevuci** [comment]
Guys forking and let's get out of here ...

**Comment by TimOliver** [comment]
I got some time this weekend, so I spent it merging in @OkiRules' Swift 5 PR. It'll be available in CocoaPods the next time I do a release.

For the record, I would like to say I did not appreciate the following things that happened here:

* Opening an issue with an empty description and a very short title, even though I provide a template on the information I need, forcing me to ask what exactly was the problem here.
* Pinging me when I didn't reply.

This is the sort of entitled behaviour that makes people not want to contribute to open source. This is a free library I contribute in my free time for no cost. Please remember that.

Thank you.
