### ISSUE TITLE
How to use CropViewController with Swift/Carthage

### ISSUE THREAD

**Issue by danqing** [TimOliver/TOCropViewController#346]
So I opened #340 but it got closed.

It looks like for Swift, if you want to use `CropViewController` class (instead of `TOCropViewController`, you have to use cocoapods. Is there a way to use it with a Carthage build?

**Comment by TimOliver** [comment]
Hi @danqing! That's right, I remember. You were trying to change the Swift sample code to use the Objective-C interface. :)

I just went through and reviewed what was going on. Yes that's correct. When building with Carthage, you must import `CropViewController.framework` from your `Carthage/Build` folder, not `TOCropViewController`. You *do not* import `TOCropViewController.framework` for Swift builds. All of that code is hidden inside `CropViewController.framework` already.

It's a bit confusing because Carthage requires the name of this repo, not the framework itself.

I've updated the README now to clarify that you need to import only `CropViewController.framework` to Swift libraries!

Did that answer all of your questions?

**Comment by danqing** [comment]
Ah I see. Totally didn't see `CropViewController.framework` - that works. Thanks for the reply @TimOliver !
