### ISSUE TITLE
MacCatalyst Signing & Capabilities issue

### ISSUE THREAD

**Issue by Hardiktspaceo** [TimOliver/TOCropViewController#366]
We are **converting our iPhone** app to **macCatalyst** compatible in which we use your library using pod. (macOS  Catalina beta 5 with Xcode beta 5)

issue is after installing pod file it gives this error 

**Signing for "CropViewController-TOCropViewControllerBundle" requires a development team. Select a development team in the Signing & Capabilities editor.**

Can you please help to solve this issue.
![Screenshot 2019-08-13 at 1 43 17 pm](https://user-images.githubusercontent.com/25246691/62925551-3580ee00-bdd0-11e9-9ce4-9387105f5f29.png)

![Screenshot 2019-08-13 at 1 48 25 pm](https://user-images.githubusercontent.com/25246691/62925941-0cad2880-bdd1-11e9-9d43-0c42fb98e855.png)

**Comment by TimOliver** [comment]
Hmm, your Team is set to “None” in that screenshot. Why haven’t you set it?

**Comment by Hardiktspaceo** [comment]
need to select team ? all other pods not showing this type of error. so i am not setting any thing in that.

**Comment by TimOliver** [comment]
Yeah, it looks like it! This is probably an aspect of CocoaPods that is
necessary because this app has a resource bundle where it keeps all of the
localized strings.

In any case, since this seems to be a CocoaPods issue, if setting the team
doesn't work, it might be worth checking the CocoaPods site if there is a
way to fix this.

Good luck!

**Comment by Hardiktspaceo** [comment]
Ok Thank you so much TimOliver.

**Comment by TimOliver** [comment]
No worries!

**Comment by dokgi88** [comment]
@TimOliver Thank You!
