### ISSUE TITLE
Suggestion: keep the Exif tags after the crop

### ISSUE THREAD

**Issue by felpsio** [TimOliver/TOCropViewController#372]
Thanks for the package.

Is it possible to add an option that makes the crop keep the EXIF tags from the original picture?

I building an app that needs the GPS tags from the pictures. Right now I have to get the tags from the original picture and then add to the cropped picture.

**Comment by TimOliver** [comment]
Hi @felpsio! Thanks a lot! I'm glad you like the library!
Hmm! That's an interesting idea! I hadn't considered it before.

 I did some research into it, and I think this is a feature better left off as something separate to the crop view controller.

`TOCropViewController` only takes in a `UIImage` as its input parameter. `UIImage` simply represents generic image data in memory, regardless of its source file format (eg PNG or JPEG). As a result, EXIF data isn't actually included with `UIImage`.

Since the library also returns a `UIImage` in memory, and doesn't actually save the image to disk itself by default, there's no place to actually insert the EXIF data back in.

Of course you could potentially just add inputs and outputs that receive a `Dictionary` of EXIF data when creating the crop view controller, and then subsequently return the exact same dictionary when the user has completed the crop operation, but this sounds like the controller just acts like a naive data store, which doesn't really add much value.

It's possible to load the EXIF data out before you pass the image to the crop view controller. I found a Medium article displaying it: https://medium.com/@maximbilan/exif-how-to-get-exif-data-in-ios-2a28af63eaac.

My recommendation is you create a second model object in charge of loading and storing the EXIF data, and then reapplying that same EXIF data to the new `UIImage` when the cropping operation is complete.

Does that sound okay to you? Thanks!

**Comment by felpsio** [comment]
Hi @TimOliver, thanks for your time thinking about the problem.

I'm already doing it: extracting the EXIF tags before using the library. I think you're right. Is better to keep extracting before using `ToCropViewController`. Thanks again :)
