### ISSUE TITLE
[Code] why is `CGContextTranslateCTM` necessary?

### ISSUE THREAD

**Issue by jozsef-vesza** [TimOliver/TOCropViewController#435]
Hi Tim 👋

First of all, I really appreciate the effort put into this project, it's well-rounded, and works well. I hope you don't mind but I've been examining the source for learning purposes, and have a question about an implementation detail.

I'm wondering why [this line](https://github.com/TimOliver/TOCropViewController/blob/master/Objective-C/TOCropViewController/Categories/UIImage+CropRotate.m#L61) is necessary. Is perhaps the drawing location different by default?

I'm sure you're very busy, and this isn't a high priority issue or anything, but if you do get the time to answer, I'd really appreciate it!

**Comment by jozsef-vesza** [comment]
After spending some time thinking about it: would it make sense to imagine the crop area at the top left corner of the image? Then translation would basically move the image up and left to move the crop target to the correct place 🤔

**Comment by TimOliver** [comment]
Hi there @jozsef-vesza! Thanks a lot! I’m glad you’ve been enjoying checking out this library’s code!

So that particular code block is in charge of generating a cropped copy of the source image, but without any rotations (The rotation code is above. Looking at it now, there’s probably a better way of handling that... 😅)

As an example, if an image was 100x100 and you wanted to crop out a section starting at point {5,5} and a size of 50x50. That particular code will allocate a new canvas that is 50x50 in size, but then before it draws the image into that canvas, it applies that matrix translation in order to move the entire canvas -5 pixels in each direction. This means that the point we specified becomes the origin, so when it draws, it will fill the canvas starting from {5,5}.

You’re correct in the the origin is in the top left corner. If that line of code wasn’t there, no matter where you wanted to crop in the image, it would always crop from the top left corner.

The iOS framework in charge of that is called Core Graphics and it’s really fun to be able to dynamically draw things with the CPU. I highly recommend checking it out.

I hope that helped! All the best! :)

**Comment by jozsef-vesza** [comment]
@TimOliver thank you so much for taking the time for this writeup! Everything is clear now 👍

**Comment by TimOliver** [comment]
@jozsef-vesza Awesome! So glad I could help! Have a good one!
