### ISSUE TITLE
Running on M1 Mac fails

### ISSUE THREAD

**Issue by danipralea** [TimOliver/TOCropViewController#526]
**Describe the bug**
Integrated the framework and tried running the project

**Expected behavior**
Run on M1 Mac

**Screenshots**
![image](https://user-images.githubusercontent.com/768893/174773476-4eb03f5b-4006-4403-ab34-1b4492bcf872.png)

**iOS Device:**
 - Device: iPhone Simulator
 - OS: iOS 15
 - Library Version - latest (`master` branch SPM integration)

**Comment by IhorShevchuk** [comment]
It looks like you should provide more details on how you integrate CropViewController to resolve this issue.
I wasn't able to reproduce this issue. 
However, based on your screenshot, I guess you have set the EXCLUDED_ARCHS option in your project to contain 'arm64' architecture in order to resolve issues with some other libraries.

**Comment by TimOliver** [comment]
Sorry for the delay! I just tested this with the SPM integration and it was working fine. Like @IhorShevchuk said, it might be some Xcode configuration issue. Thanks!
