### ISSUE TITLE
After croppping and rotating, cropRectFrame is wrong.

### ISSUE THREAD

**Issue by yongseongkim** [TimOliver/TOCropViewController#79]
I applied TOCropView to my application.
But there is a bug.
When I rotate the image after cropping both width and height(smaller than original image),
the result frame is wrong

**Comment by TimOliver** [comment]
Thanks for the issue! Wrong in what way?

**Comment by yongseongkim** [comment]
After cropping and rotating, out of photo range. 
just show black screen with white grid overlay view.
And one more rotating, original image matched white grid overlay view size shows. (not cropped image)

**Comment by TimOliver** [comment]
Uhhh, why are you embedding `TOCropView` into another view and not simply using `TOCropViewController`?

I never intended for `TOCropView` to be used outside of `TOCropViewController`, and so it relies on functionality in `TOCropViewController` itself in order to perform its layout properly. If you embed it in another view controller without this functionality, it may not work properly.

I'd recommend just using `TOCropViewController` and changing its theme to match the design you want. If you still want to embed it in another view controller, you'll have to go through the `TOCropViewController` class and copy out the necessary logic for your own view controller.

Sorry!

**Comment by yongseongkim** [comment]
Oh... It also happen in TOCropViewController.
Just play your crop view controller example.
First, crop smaller than original image.
Second, just rotate twice(180').
I don't know why many people don't say this bug.
<img width="464" alt="2016-05-05 10 16 04" src="https://cloud.githubusercontent.com/assets/8086744/15033839/698f8276-12aa-11e6-9a33-29359820cdc5.png">

**Comment by TimOliver** [comment]
Ahh! I found out how to reproduce it. Sorry about that!
I just fixed it. Thanks for reporting it! :)
