### ISSUE TITLE
<UIVisualEffectView 0x7fe2130553e0> is being asked to animate its opacity. This will cause the effect to appear broken until opacity returns to 1.

### ISSUE THREAD

**Issue by d3ce1t** [TimOliver/TOCropViewController#80]
I get this warning whenever I cancel or accept the TOCropViewController. In order to reproduce this, follow these steps:

1) Open TOCropViewControllerExample project
2) Run on Simulator
3) Open an image for cropping
4) Tap Cancel or Done and the described warning will appear in console. 

### Expected Behavior

No warning in console

### Actual Behavior

Warning in console

**Comment by TimOliver** [comment]
Hi! Thanks for the report!

This warning can't be helped. It's printed by the system when performing the alpha fade animation on the `UIVisualEffectView` instance that creates the blurry effect outside the region of the crop box. While the warning itself says the effect will look broken, I thought it looked fine. Unfortunately, since it's on the system level, it can't be suppressed.

However, I did a bit of research, and discovered there's an official, better way to perform the animation in iOS 9, that creates a blurry animation effect similar to dragging down on the iOS Home Screen to open Spotlight. 

I've since modified the library to use this animation method on iOS 9, and the console warning has gone away. It will, however, still appear if the device in question is running iOS 8.

Thanks a lot for the help!

**Comment by d3ce1t** [comment]
Thank you very much for your quickly fix :).

I've just tested it on Simulator from iOS version 7 to 9 and I can confirm that aforementioned warning no longer appears in either of the tested versions. I would have expected to appear in 7 and 8 after your words. But it doesn't. So maybe something else has been changed?. Anyway, I only mention to put it in your knowledgement.

Thank you again for your great work!

**Comment by TimOliver** [comment]
Haha no problems! Thanks for reporting it! I was going to ignore it forever!

Uh-oh. Really? It SHOULD still be happening in iOS 8. It won't happen in iOS 7 since `UIVisualEffectView` wasn't available then, so it's using a normal `UIToolbar` instead.

I might need to test that again... XD
